
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author alex22
 */
public class actorsinsert extends javax.swing.JFrame {
Connection con = null;
    PreparedStatement pstmnt = null;
    PreparedStatement pstmnt1=null;
    Statement stmnt = null;
    ResultSet rs = null;
    DefaultTableModel dm;
    public actorsinsert() throws ClassNotFoundException, SQLException {
        Class.forName("org.apache.derby.jdbc.EmbeddedDriver");
       String curr = System.getProperty("user.dir");
         con =DriverManager.getConnection("jdbc:derby:"+curr+"/tvseries","root","sujithmenon");
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        actor_id = new javax.swing.JTextField();
        actor_name = new javax.swing.JTextField();
        dob = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        show_id1 = new javax.swing.JTextField();
        noe = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        actor_insert = new javax.swing.JButton();
        actor_reset = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Actor ID");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 12, 175, 36));

        jLabel10.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Actor Name");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 60, 175, 36));

        jLabel11.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Date Of Birth");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 103, 175, 50));

        jLabel12.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Age");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 156, 175, 36));

        jLabel13.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Show ID");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 205, 175, 35));

        jLabel14.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("No. Of Episodes");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 252, 175, 36));

        actor_id.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        getContentPane().add(actor_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 12, 222, 36));

        actor_name.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        getContentPane().add(actor_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 60, 222, 36));

        dob.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        getContentPane().add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 108, 222, 36));

        age.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        getContentPane().add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 157, 222, 36));

        show_id1.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        getContentPane().add(show_id1, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 205, 222, 35));

        noe.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        getContentPane().add(noe, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 252, 222, 36));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 255, 255));
        jLabel15.setText("yyyy-mm-dd");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(535, 118, 90, -1));

        actor_insert.setBackground(new java.awt.Color(255, 255, 255));
        actor_insert.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        actor_insert.setForeground(new java.awt.Color(0, 51, 255));
        actor_insert.setText("Submit");
        actor_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actor_insertActionPerformed(evt);
            }
        });
        getContentPane().add(actor_insert, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 80, 40));

        actor_reset.setBackground(new java.awt.Color(255, 255, 255));
        actor_reset.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        actor_reset.setForeground(new java.awt.Color(255, 0, 51));
        actor_reset.setText("Reset");
        actor_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actor_resetActionPerformed(evt);
            }
        });
        getContentPane().add(actor_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, 70, 40));

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/daredevil(1).jpg"))); // NOI18N
        jLabel16.setText("jLabel16");
        jLabel16.setName("Submit"); // NOI18N
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void actor_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actor_insertActionPerformed
        try{

            String s = "Insert into Actors(actor_id,Actor_name,DOB,age) values(?,?,?,?)";

            String s1 = "Insert into connectiontable (aid,sid,noe) values(?,?,?)";
            pstmnt= con.prepareStatement(s);
            pstmnt1= con.prepareStatement(s1);
            pstmnt.setString(1,actor_id.getText());
            pstmnt.setString(2,actor_name.getText());
            pstmnt.setString(3,dob.getText());
            pstmnt.setString(4,age.getText());
            pstmnt1.setString(1,actor_id.getText());
            pstmnt1.setString(2,show_id1.getText());
            pstmnt1.setString(3,noe.getText());
            pstmnt.executeUpdate();
            pstmnt1.executeUpdate();
            JOptionPane.showMessageDialog(null,"Inserted");

        } catch(SQLException | HeadlessException e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_actor_insertActionPerformed

    private void actor_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actor_resetActionPerformed
        try{
            actor_id.setText("");
            actor_name.setText("");
            dob.setText("");
            age.setText("");
            show_id1.setText("");
            noe.setText("");

        }
        catch(Exception e)
        {JOptionPane.showMessageDialog(null,e);

        }
    }//GEN-LAST:event_actor_resetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(actorsinsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(actorsinsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(actorsinsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(actorsinsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new actorsinsert().setVisible(true);
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(actorsinsert.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField actor_id;
    private javax.swing.JButton actor_insert;
    private javax.swing.JTextField actor_name;
    private javax.swing.JButton actor_reset;
    private javax.swing.JTextField age;
    private javax.swing.JTextField dob;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField noe;
    private javax.swing.JTextField show_id1;
    // End of variables declaration//GEN-END:variables
}
