
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author alex22
 */
public class actorquery extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement pstmnt = null;
    PreparedStatement pstmnt1=null;
    Statement stmnt = null;
    ResultSet rs = null;
    DefaultTableModel dm;
    public actorquery() throws ClassNotFoundException, SQLException {
        Class.forName("org.apache.derby.jdbc.EmbeddedDriver");
        
        String curr = System.getProperty("user.dir");
         con =DriverManager.getConnection("jdbc:derby:"+curr+"/tvseries","root","sujithmenon");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        qactorname = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        qasc = new javax.swing.JRadioButton();
        qdesc = new javax.swing.JRadioButton();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jScrollPane5 = new javax.swing.JScrollPane();
        actortable = new javax.swing.JTable();
        jButton8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(1, 1, 1));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel33.setFont(new java.awt.Font("Gargi", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(254, 254, 254));
        jLabel33.setText("Enter the ACTOR NAME to query");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));
        jPanel1.add(qactorname, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 166, -1));

        jButton7.setBackground(new java.awt.Color(0, 0, 0));
        jButton7.setForeground(new java.awt.Color(255, 0, 0));
        jButton7.setText("GO");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 60, -1));

        jLabel34.setFont(new java.awt.Font("Gargi", 1, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(254, 254, 254));
        jLabel34.setText("Sort ACTOR list by shows in ");
        jPanel1.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, -1));

        qasc.setBackground(new java.awt.Color(0, 0, 51));
        qasc.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        qasc.setForeground(new java.awt.Color(255, 255, 255));
        qasc.setText("Ascending order");
        qasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qascActionPerformed(evt);
            }
        });
        jPanel1.add(qasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, -1, -1));

        qdesc.setBackground(new java.awt.Color(0, 0, 51));
        qdesc.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        qdesc.setForeground(new java.awt.Color(255, 255, 255));
        qdesc.setText("Descending order");
        qdesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qdescActionPerformed(evt);
            }
        });
        jPanel1.add(qdesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, -1, -1));

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 50, 136));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 620, 10));

        jScrollPane5.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane5.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        actortable.setBackground(new java.awt.Color(0, 0, 0));
        actortable.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        actortable.setForeground(new java.awt.Color(255, 255, 0));
        actortable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane5.setViewportView(actortable);

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 600, 236));

        jButton8.setBackground(new java.awt.Color(0, 0, 0));
        jButton8.setForeground(new java.awt.Color(255, 0, 0));
        jButton8.setText("GO");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 60, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/narcos-netflix-logo-e144116767.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 190));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try {   dm=(DefaultTableModel)actortable.getModel();
            dm.setColumnCount(0);
            dm.setRowCount(0);
            
            pstmnt= con.prepareStatement("Select a.actor_id,a.Actor_name,a.DOB,a.age,b.sid,b.noe from Actors a, connectiontable b where a.Actor_name like '"+qactorname.getText()+"%' and b.aid = a.actor_id");
            rs = pstmnt.executeQuery();
           
            dm.addColumn("Actor ID");
            dm.addColumn("Actor name");
            dm.addColumn("DOB");
            dm.addColumn("Age");
            dm.addColumn("Show ID");
            dm.addColumn("No. of Episodes");
            while(rs.next())
            {String aarray[]= {rs.getString("actor_id"),rs.getString("Actor_name"),rs.getString("DOB"),rs.getString("age"),rs.getString("sid"),rs.getString("noe")};
                dm.addRow(aarray);
            }
        }     catch(Exception e)
        {JOptionPane.showMessageDialog(null,e);}
    }//GEN-LAST:event_jButton7ActionPerformed

    private void qascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qascActionPerformed
        if(qasc.isSelected())
        qdesc.setSelected(false);
    }//GEN-LAST:event_qascActionPerformed

    private void qdescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qdescActionPerformed
        if(qdesc.isSelected())
        qasc.setSelected(false);
    }//GEN-LAST:event_qdescActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        try {dm=(DefaultTableModel)actortable.getModel();
            dm.setColumnCount(0);
            dm.setRowCount(0);
            if (qasc.isSelected())
            { 
                pstmnt= con.prepareStatement("Select a.actor_id,a.Actor_name,a.DOB,a.age,b.sid,b.noe from Actors a, connectiontable b where b.aid = a.actor_id order by b.sid");
                rs = pstmnt.executeQuery();
                dm.addColumn("Actor ID");
                dm.addColumn("Actor name");
                dm.addColumn("DOB");
                dm.addColumn("Age");
                dm.addColumn("Show ID");
                dm.addColumn("No of Episodes");
                while(rs.next())
                {String aarray[]= {rs.getString("actor_id"),rs.getString("Actor_name"),rs.getString("DOB"),rs.getString("age"),rs.getString("sid"),rs.getString("noe")};
                    dm.addRow(aarray);
                }
            }
            if(qdesc.isSelected())
            {
                pstmnt= con.prepareStatement("Select a.actor_id,a.Actor_name,a.DOB,a.age,b.sid,b.noe from Actors a, connectiontable b where b.aid = a.actor_id order by b.sid desc");
                rs = pstmnt.executeQuery();
                dm.addColumn("Actor ID");
                dm.addColumn("Actor name");
                dm.addColumn("DOB");
                dm.addColumn("Age");
                dm.addColumn("Show ID");
                dm.addColumn("No. of Episodes");
                while(rs.next())
                {String aarray[]= {rs.getString("actor_id"),rs.getString("Actor_name"),rs.getString("DOB"),rs.getString("age"),rs.getString("sid"),rs.getString("noe")};
                    dm.addRow(aarray);
                }}}  catch(Exception e)
                {JOptionPane.showMessageDialog(null,e);}
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(actorquery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(actorquery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(actorquery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(actorquery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new actorquery().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(actorquery.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(actorquery.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable actortable;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTextField qactorname;
    private javax.swing.JRadioButton qasc;
    private javax.swing.JRadioButton qdesc;
    // End of variables declaration//GEN-END:variables
}
