
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author alex22
 */
public class awardquery extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement pstmnt = null;
    PreparedStatement pstmnt1=null;
    Statement stmnt = null;
    ResultSet rs = null;
    DefaultTableModel dm;
    public awardquery() throws ClassNotFoundException, SQLException {
        Class.forName("org.apache.derby.jdbc.EmbeddedDriver");
        String curr = System.getProperty("user.dir");
         con = DriverManager.getConnection("jdbc:derby:"+curr+"/tvseries","root","sujithmenon");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        firstrb = new javax.swing.JRadioButton();
        secondrb = new javax.swing.JRadioButton();
        thirdrb = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 157, 600, 10));

        table.setBackground(new java.awt.Color(0, 0, 0));
        table.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        table.setForeground(new java.awt.Color(255, 255, 51));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 173, 520, 260));

        jLabel1.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SORT TV SHOWS BASED ON RATING");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 480, -1));

        firstrb.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        firstrb.setForeground(new java.awt.Color(255, 255, 255));
        firstrb.setText("Ratings greater than 90%");
        firstrb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstrbActionPerformed(evt);
            }
        });
        jPanel1.add(firstrb, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        secondrb.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        secondrb.setForeground(new java.awt.Color(255, 255, 255));
        secondrb.setText("Ratings greater than 85%");
        secondrb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondrbActionPerformed(evt);
            }
        });
        jPanel1.add(secondrb, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        thirdrb.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        thirdrb.setForeground(new java.awt.Color(255, 255, 255));
        thirdrb.setText("Ratings below 85%");
        thirdrb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thirdrbActionPerformed(evt);
            }
        });
        jPanel1.add(thirdrb, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 180, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("DejaVu Serif Condensed", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("GO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/breaking-bad(1).jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 160));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void firstrbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstrbActionPerformed
        if(firstrb.isSelected())
        {
            secondrb.setSelected(false);
            thirdrb.setSelected(false);
            
        }
    }//GEN-LAST:event_firstrbActionPerformed

    private void secondrbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondrbActionPerformed
         if(secondrb.isSelected())
        {
            firstrb.setSelected(false);
            thirdrb.setSelected(false);
            
        }
    }//GEN-LAST:event_secondrbActionPerformed

    private void thirdrbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thirdrbActionPerformed
        if(thirdrb.isSelected())
        {
            firstrb.setSelected(false);
            secondrb.setSelected(false);
            
        }
    }//GEN-LAST:event_thirdrbActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            dm = (DefaultTableModel) table.getModel();
            dm.setColumnCount(0);
            dm.setRowCount(0);
            if(firstrb.isSelected())
            {   
                pstmnt= con.prepareStatement("Select a.show_name, a.no_of_seasons from shows a, rating b where ((b.imdb+b.tv+b.rotten)/3)>9.0 and b.sid = a.sid");
                rs = pstmnt.executeQuery();
                dm.addColumn("SHOW NAME");
                dm.addColumn("NO OF SEASONS");
                while(rs.next())
                {
                    String ar[] = {rs.getString("show_name"),rs.getString("no_of_seasons")};
                    dm.addRow(ar);
                }
                }
             if(secondrb.isSelected())
            {   
                pstmnt= con.prepareStatement("Select a.show_name, a.no_of_seasons from shows a, rating b where ((b.imdb+b.tv+b.rotten)/3)>8.5 and b.sid = a.sid");
                rs = pstmnt.executeQuery();
                dm.addColumn("SHOW NAME");
                dm.addColumn("NO OF SEASONS");
                while(rs.next())
                {
                    String ar[] = {rs.getString("show_name"),rs.getString("no_of_seasons")};
                    dm.addRow(ar);
                }
                }
              if(thirdrb.isSelected())
            {   
                pstmnt= con.prepareStatement("Select a.show_name, a.no_of_seasons from shows a, rating b where ((b.imdb+b.tv+b.rotten)/3)<8.5 and b.sid = a.sid");
                rs = pstmnt.executeQuery();
                dm.addColumn("SHOW NAME");
                dm.addColumn("NO OF SEASONS");
                while(rs.next())
                {
                    String ar[] = {rs.getString("show_name"),rs.getString("no_of_seasons")};
                    dm.addRow(ar);
                }
                }
        } catch(SQLException e)
        {JOptionPane.showMessageDialog(null,e);}
     
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(awardquery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(awardquery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(awardquery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(awardquery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new awardquery().setVisible(true);
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(awardquery.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton firstrb;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton secondrb;
    private javax.swing.JTable table;
    private javax.swing.JRadioButton thirdrb;
    // End of variables declaration//GEN-END:variables
}
