
import java.awt.HeadlessException;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author alex22
 */
public class awardinsert extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement pstmnt = null;
    PreparedStatement pstmnt1=null;
    Statement stmnt = null;
    ResultSet rs = null;
    DefaultTableModel dm;
    public awardinsert() throws ClassNotFoundException, SQLException {
         Class.forName("org.apache.derby.jdbc.EmbeddedDriver");
        String curr = System.getProperty("user.dir");
         con =DriverManager.getConnection("jdbc:derby:"+curr+"/tvseries","root","sujithmenon");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        imdb = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        rt = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        tv = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        show_id2 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        actor_id1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        desc = new javax.swing.JTextArea();
        award_submit = new javax.swing.JButton();
        award_reset = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(1, 1, 1));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Show ID");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 180, 40));

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Ratings");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 110, 34));

        jLabel19.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(254, 254, 254));
        jLabel19.setText("IMDB");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 60, 30));

        imdb.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        getContentPane().add(imdb, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 84, 28));

        jLabel20.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(254, 254, 254));
        jLabel20.setText("Rotten Tomato");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 120, 120, 30));

        rt.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        rt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rtActionPerformed(evt);
            }
        });
        getContentPane().add(rt, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 86, 28));

        jLabel21.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(254, 254, 254));
        jLabel21.setText("(IN PERCENTAGE FORM)");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 170, 30));

        tv.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        tv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tvActionPerformed(evt);
            }
        });
        getContentPane().add(tv, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 85, 28));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 163, 560, 10));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 570, 10));

        show_id2.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        getContentPane().add(show_id2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 200, 40));

        jLabel22.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Awards");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel23.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(254, 254, 254));
        jLabel23.setText("Actor ID");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 210, 100, 30));

        actor_id1.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        getContentPane().add(actor_id1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 153, 30));

        jLabel24.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(254, 254, 254));
        jLabel24.setText("Award Description");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 180, 29));

        desc.setColumns(20);
        desc.setRows(5);
        jScrollPane1.setViewportView(desc);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 260, 70));

        award_submit.setBackground(new java.awt.Color(255, 255, 255));
        award_submit.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        award_submit.setForeground(new java.awt.Color(0, 51, 255));
        award_submit.setText("Submit");
        award_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                award_submitActionPerformed(evt);
            }
        });
        getContentPane().add(award_submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 90, 30));

        award_reset.setBackground(new java.awt.Color(255, 255, 255));
        award_reset.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        award_reset.setForeground(new java.awt.Color(255, 0, 51));
        award_reset.setText("Reset");
        award_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                award_resetActionPerformed(evt);
            }
        });
        getContentPane().add(award_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 80, 30));

        jLabel25.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(254, 254, 254));
        jLabel25.setText("TV.com");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 70, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/czkha10xuae2dos.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 0, 620, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rtActionPerformed

    private void award_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_award_submitActionPerformed
        try
        {   if(!"".equals(actor_id1.getText()))
        { 
                    CallableStatement cs = con.prepareCall("{ call proc_name(?, ?,?)}");
                    cs.setString(1,show_id2.getText());
                    cs.setString(2,actor_id1.getText());
                    cs.setString(3,desc.getText());
                    cs.execute();
                    
        }   
               if(!"".equals(imdb.getText()))
               {String s1 = "Insert into rating (sid,imdb,rotten,TV) values (?,?,?,?)";
                pstmnt1=con.prepareStatement(s1);
                pstmnt1.setString(1,show_id2.getText());
                pstmnt1.setString(2,imdb.getText());
                pstmnt1.setString(3,rt.getText());
                pstmnt1.setString(4,tv.getText());
                pstmnt1.executeUpdate();
                JOptionPane.showMessageDialog(null,"INSERT TRIGGER EXECUTED");
                JOptionPane.showMessageDialog(null,"Converted percentage rating to floating point");
               }
                
            JOptionPane.showMessageDialog(null,"Inserted");

        }
        catch(SQLException | HeadlessException e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_award_submitActionPerformed

    private void award_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_award_resetActionPerformed
        try{
            actor_id1.setText("");
            show_id2.setText("");
            desc.setText("");
            rt.setText("");
            imdb.setText("");
            tv.setText("");

        }
        catch(Exception e)
        {   JOptionPane.showMessageDialog(null,e);

        }
    }//GEN-LAST:event_award_resetActionPerformed

    private void tvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tvActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(awardinsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(awardinsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(awardinsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(awardinsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new awardinsert().setVisible(true);
                } catch (ClassNotFoundException | SQLException ex) {
                    Logger.getLogger(awardinsert.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField actor_id1;
    private javax.swing.JButton award_reset;
    private javax.swing.JButton award_submit;
    private javax.swing.JTextArea desc;
    private javax.swing.JTextField imdb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField rt;
    private javax.swing.JTextField show_id2;
    private javax.swing.JTextField tv;
    // End of variables declaration//GEN-END:variables
}
