
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author alex22
 */
public class showquery extends javax.swing.JFrame {
Connection con = null;
    PreparedStatement pstmnt = null;
    PreparedStatement pstmnt1=null;
    Statement stmnt = null;
    ResultSet rs = null;
    DefaultTableModel dm;

    public showquery() throws ClassNotFoundException, SQLException {
        Class.forName("org.apache.derby.jdbc.EmbeddedDriver");
        String curr = System.getProperty("user.dir");
         con =DriverManager.getConnection("jdbc:derby:"+curr+"/tvseries","root","sujithmenon");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator5 = new javax.swing.JSeparator();
        asc = new javax.swing.JRadioButton();
        qshowname = new javax.swing.JTextField();
        descb = new javax.swing.JRadioButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        showstable = new javax.swing.JTable();
        jLabel32 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel31 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(1, 1, 1));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 701, -1));

        asc.setBackground(new java.awt.Color(1, 1, 1));
        asc.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        asc.setForeground(new java.awt.Color(254, 254, 254));
        asc.setText("Ascending");
        asc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ascActionPerformed(evt);
            }
        });
        jPanel1.add(asc, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, -1, -1));
        jPanel1.add(qshowname, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 71, 180, -1));

        descb.setBackground(new java.awt.Color(0, 51, 51));
        descb.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        descb.setForeground(new java.awt.Color(254, 254, 254));
        descb.setText("Descending");
        descb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descbActionPerformed(evt);
            }
        });
        jPanel1.add(descb, new org.netbeans.lib.awtextra.AbsoluteConstraints(531, 95, -1, -1));

        jButton5.setBackground(new java.awt.Color(255, 0, 0));
        jButton5.setFont(new java.awt.Font("Nimbus Sans L", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("GO");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 126, 80, 30));

        jButton6.setBackground(new java.awt.Color(255, 0, 0));
        jButton6.setFont(new java.awt.Font("WenQuanYi Micro Hei", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("GO");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(462, 123, 70, 30));

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        showstable.setBackground(new java.awt.Color(0, 0, 0));
        showstable.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        showstable.setForeground(new java.awt.Color(0, 255, 204));
        showstable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(showstable);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 660, 224));

        jLabel32.setFont(new java.awt.Font("FreeSans", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(254, 254, 254));
        jLabel32.setText("Sort all the TV SHOWS By");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(417, 24, -1, -1));

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(369, 0, 30, 160));

        jLabel31.setFont(new java.awt.Font("FreeSans", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(254, 254, 254));
        jLabel31.setText("Enter the SHOW NAME to query");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 24, 292, 41));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/frnds(1).jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 170));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ascActionPerformed
        if(asc.isSelected())
        descb.setSelected(false);
    }//GEN-LAST:event_ascActionPerformed

    private void descbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descbActionPerformed
        if(descb.isSelected())
        asc.setSelected(false);
    }//GEN-LAST:event_descbActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        try{dm=(DefaultTableModel)showstable.getModel();
            dm.setColumnCount(0);
            dm.setRowCount(0);

           
            pstmnt= con.prepareStatement("Select a.sid ,a.show_name, a.yr_release,a.no_of_seasons, b.lang1,b.lang2,b.Country,b.Banner"
                    + " from shows a, details b where a.show_name like '" + qshowname.getText() + "%' And b.sid = "
                            + "(select q.sid from shows q where q.show_name = '" + qshowname.getText() + "')");
            rs = pstmnt.executeQuery();
            dm.addColumn("Show ID");
            dm.addColumn("Show name");
            dm.addColumn("Date of Release");
            dm.addColumn("No.Of Episodes");
            dm.addColumn("Language1");
            dm.addColumn("Language2");
            dm.addColumn("Country");
            dm.addColumn("Banner");
            while(rs.next())
            { String qarray[]={rs.getString("sid"),rs.getString("show_name"),rs.getString("yr_release"),
                rs.getString("no_of_seasons"),rs.getString("lang1"),rs.getString("lang2"),rs.getString("Country"),rs.getString("Banner")};
                dm.addRow(qarray);

            }
        }

        catch(Exception e)
        {JOptionPane.showMessageDialog(null,e);}
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try{dm=(DefaultTableModel)showstable.getModel();
            dm.setColumnCount(0);
            dm.setRowCount(0);
            if(asc.isSelected())
            {
                
                pstmnt= con.prepareStatement("Select a.sid ,a.show_name, a.yr_release,a.no_of_seasons, b.lang1,b.lang2, b.Country,b.Banner from shows a, details b where a.sid = b.sid order by a.show_name");
                rs = pstmnt.executeQuery();
                dm.addColumn("Show ID");
                dm.addColumn("Show name");
                dm.addColumn("Date of Release");
                dm.addColumn("No.Of Episodes");
                dm.addColumn("Language1");
                dm.addColumn("Language2");
                dm.addColumn("Country");
                dm.addColumn("Banner");
                while(rs.next())
                { String qarray[]={rs.getString("sid"),rs.getString("show_name"),rs.getString("yr_release"),rs.getString("no_of_seasons"),rs.getString("lang1"),rs.getString("lang2"),rs.getString("Country"),rs.getString("Banner")};
                    dm.addRow(qarray);

                }
            }
            if(descb.isSelected())
            {
               
                pstmnt= con.prepareStatement("Select a.sid ,a.show_name, a.yr_release,a.no_of_seasons, b.lang1,b.lang2, b.Country,b.Banner from shows a, details b where a.sid = b.sid order by a.show_name desc");
                rs = pstmnt.executeQuery();
                dm.addColumn("Show ID");
                dm.addColumn("Show name");
                dm.addColumn("Date of Release");
                dm.addColumn("No.Of Episodes");
                dm.addColumn("Language1");
                dm.addColumn("Language 2");
                dm.addColumn("Country");
                dm.addColumn("Banner");
                while(rs.next())
                { String qarray[]={rs.getString("sid"),rs.getString("show_name"),rs.getString("yr_release"),rs.getString("no_of_seasons"),rs.getString("lang1"),rs.getString("lang2"),rs.getString("Country"),rs.getString("Banner")};
                    dm.addRow(qarray);

                }
            }
        }

        catch(Exception e)
        {JOptionPane.showMessageDialog(null,e);}
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(showquery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(showquery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(showquery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(showquery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new showquery().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(showquery.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(showquery.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton asc;
    private javax.swing.JRadioButton descb;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField qshowname;
    private javax.swing.JTable showstable;
    // End of variables declaration//GEN-END:variables
}
