
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author alex22
 */
public class showsinsert extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement pstmnt = null;
    PreparedStatement pstmnt1=null;
    Statement stmnt = null;
    ResultSet rs = null;
    DefaultTableModel dm;
    public showsinsert() throws ClassNotFoundException, SQLException {
        Class.forName("org.apache.derby.jdbc.EmbeddedDriver");
        String curr = System.getProperty("user.dir");
         con =DriverManager.getConnection("jdbc:derby:"+curr+"/tvseries","root","sujithmenon");
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        show_id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        show_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        yr = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        show_insert = new javax.swing.JButton();
        nos = new javax.swing.JTextField();
        lang1 = new javax.swing.JTextField();
        banner = new javax.swing.JTextField();
        country = new javax.swing.JTextField();
        shows_reset = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lang = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Show ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 146, 36));

        show_id.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        show_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_idActionPerformed(evt);
            }
        });
        getContentPane().add(show_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 274, 36));

        jLabel2.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Show Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 146, 36));

        show_name.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        show_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_nameActionPerformed(evt);
            }
        });
        getContentPane().add(show_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 274, 36));

        jLabel3.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Release Date");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 146, 36));

        yr.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        getContentPane().add(yr, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 274, 36));

        jLabel6.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Country");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 146, 36));

        jLabel7.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Language 2");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, 110, 36));

        show_insert.setBackground(new java.awt.Color(255, 255, 255));
        show_insert.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        show_insert.setForeground(new java.awt.Color(0, 51, 255));
        show_insert.setText("Submit");
        show_insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                show_insertActionPerformed(evt);
            }
        });
        getContentPane().add(show_insert, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 90, 40));

        nos.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        getContentPane().add(nos, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 130, 36));

        lang1.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        getContentPane().add(lang1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 160, 36));

        banner.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        getContentPane().add(banner, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 140, 36));

        country.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        getContentPane().add(country, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 274, 36));

        shows_reset.setBackground(new java.awt.Color(255, 255, 255));
        shows_reset.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        shows_reset.setForeground(new java.awt.Color(255, 0, 51));
        shows_reset.setText("Reset");
        shows_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shows_resetActionPerformed(evt);
            }
        });
        getContentPane().add(shows_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 90, 40));

        jLabel9.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("No. Of Seasons");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 150, 36));

        jLabel10.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Banner");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 90, 36));

        jLabel11.setFont(new java.awt.Font("DejaVu Sans Condensed", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Language 1");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 110, 36));

        lang.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        getContentPane().add(lang, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, 160, 36));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 255, 255));
        jLabel15.setText("yyyy-mm-dd");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 90, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/got rz.jpg"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void show_insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_insertActionPerformed
        try {

            String s = "insert into shows(sid,show_name,yr_release,no_of_Seasons) values(?,?,?,?)";
            String s2 = "insert into details (sid,lang1,country,banner,lang2) values (?,?,?,?,?)";
            pstmnt = con.prepareStatement(s);
            pstmnt1 = con.prepareStatement(s2);
            pstmnt.setString(1,show_id.getText());
            pstmnt.setString(2,show_name.getText());
            pstmnt.setString(3,yr.getText());
            pstmnt.setString(4,nos.getText());
            pstmnt1.setString(1,show_id.getText());
            pstmnt1.setString(2,lang1.getText());
            pstmnt1.setString(3,country.getText());
            pstmnt1.setString(4,banner.getText());
            pstmnt1.setString(5,lang.getText());
            pstmnt.executeUpdate();
            pstmnt1.executeUpdate();

            JOptionPane.showMessageDialog(null,"Inserted");

        }
        catch(SQLException | HeadlessException e){
            JOptionPane.showMessageDialog(null,e);
        }

    }//GEN-LAST:event_show_insertActionPerformed

    private void shows_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shows_resetActionPerformed
        try{
            country.setText("");
            show_id.setText("");
            lang1.setText("");
            banner.setText("");
            show_name.setText("");
            yr.setText("");
            nos.setText("");
            lang.setText("");

        }
        catch(Exception e)
        {JOptionPane.showMessageDialog(null,e);

        }
    }//GEN-LAST:event_shows_resetActionPerformed

    private void show_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_show_idActionPerformed

    private void show_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_show_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_show_nameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(showsinsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(showsinsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(showsinsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(showsinsert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new showsinsert().setVisible(true);
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(showsinsert.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField banner;
    private javax.swing.JTextField country;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lang;
    private javax.swing.JTextField lang1;
    private javax.swing.JTextField nos;
    private javax.swing.JTextField show_id;
    private javax.swing.JButton show_insert;
    private javax.swing.JTextField show_name;
    private javax.swing.JButton shows_reset;
    private javax.swing.JTextField yr;
    // End of variables declaration//GEN-END:variables
}
