
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author alex22
 */
public class viewaward extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement pstmnt = null;
    PreparedStatement pstmnt1=null;
    Statement stmnt = null;
    ResultSet rs = null;
    DefaultTableModel dm;
    public viewaward() throws ClassNotFoundException, SQLException {
        Class.forName("org.apache.derby.jdbc.EmbeddedDriver");
        String curr = System.getProperty("user.dir");
         con =DriverManager.getConnection("jdbc:derby:"+curr+"/tvseries","root","sujithmenon");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ratingsrb = new javax.swing.JRadioButton();
        awardsrb = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel30 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(1, 1, 1));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ratingsrb.setBackground(new java.awt.Color(254, 254, 254));
        ratingsrb.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        ratingsrb.setForeground(new java.awt.Color(254, 254, 254));
        ratingsrb.setText("Rating");
        ratingsrb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ratingsrbActionPerformed(evt);
            }
        });
        jPanel1.add(ratingsrb, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        awardsrb.setBackground(new java.awt.Color(102, 102, 102));
        awardsrb.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        awardsrb.setForeground(new java.awt.Color(254, 254, 254));
        awardsrb.setText("Awards");
        awardsrb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                awardsrbActionPerformed(evt);
            }
        });
        jPanel1.add(awardsrb, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 52, -1, -1));

        jButton3.setBackground(new java.awt.Color(254, 254, 254));
        jButton3.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(1, 1, 1));
        jButton3.setText("GO");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 86, 51, -1));

        table.setBackground(new java.awt.Color(0, 0, 0));
        table.setForeground(new java.awt.Color(255, 255, 255));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(table);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 471, 184));

        jLabel30.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Select the table whose all records should be displayed.");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/flash(1).jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 160));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 375, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ratingsrbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ratingsrbActionPerformed
        if(ratingsrb.isSelected())
        { 
            awardsrb.setSelected(false);
            
        }
    }//GEN-LAST:event_ratingsrbActionPerformed

    private void awardsrbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_awardsrbActionPerformed
        if(awardsrb.isSelected())
        {
            ratingsrb.setSelected(false);
            
        }
    }//GEN-LAST:event_awardsrbActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        try
        { dm=(DefaultTableModel)table.getModel();
            dm.setColumnCount(0);
            dm.setRowCount(0);

            
            if(ratingsrb.isSelected())
            {
                dm = (DefaultTableModel) table.getModel();
                dm.addColumn("Series ID");
                dm.addColumn("IMDB");
                dm.addColumn("Rotten Tomato");
                dm.addColumn("TV.com");
                stmnt = con.createStatement();
                rs = stmnt.executeQuery("select * from rating");
                while(rs.next())
                { String aarray[]= {rs.getString("sid"),rs.getString("imdb"),rs.getString("rotten"),rs.getString("Tv")};
                    dm.addRow(aarray);
                }
            }
            if(awardsrb.isSelected())
            {
                dm = (DefaultTableModel) table.getModel();
                dm.addColumn("Series ID");
                dm.addColumn("Actor ID");
                dm.addColumn("Award Description");
                stmnt = con.createStatement();
                rs = stmnt.executeQuery("select * from Awards");
                while(rs.next())
                { String aarray[]= {rs.getString("sid"),rs.getString("aid"),rs.getString("A_desc")};
                    dm.addRow(aarray);
                }
            }
            
        }        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewaward.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewaward.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewaward.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewaward.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new viewaward().setVisible(true);
                } catch (ClassNotFoundException | SQLException ex) {
                    Logger.getLogger(viewaward.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton awardsrb;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton ratingsrb;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
